name: movibus
description: "Una aplicación móvil para la gestión de transporte público institucional, que permite a los usuarios consultar horarios y rutas de autobuses en tiempo real."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/IconoTransporte.png"

flutter:
  uses-material-design: true
